version: '3'

services:
  node:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: node:venmo
    container_name: node
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
      - "4200:4200"
    volumes:
      - ./:/home/node/shared
    networks:
      - app-network
    tty: true
    stdin_open: true
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
